#import <UIKit/UIKit.h>
#import <AVFoundation/AVFoundation.h>

//Header below is generated by compiler
#import "NativeNavigation-Swift.h"

#include "MainWindow.h"
#include "MainComponent.h"


//-----------------------------------------------------------

MainWindow::MainWindow (String name)  : DocumentWindow (name,
                                                        Colours::lightgrey,
                                                        DocumentWindow::allButtons)
{
    UIWindow* window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    window.backgroundColor = [UIColor grayColor];
    
    UIView* juceView = [[UIView alloc] initWithFrame: [[UIScreen mainScreen] bounds]];
    MainWindow::addComponentToUIView (mainComponent.getObject(), juceView);

    JuceViewController* juceViewController = [[JuceViewController alloc] initWithContentView: juceView];
    
    juceViewController.contentView = juceView;
    UINavigationController* detailNavController;
    
    MasterViewController* masterViewController = [[MasterViewController alloc] init];
    
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad)
    {
        UISplitViewController* splitVC = [[UISplitViewController alloc] init];
        [window setRootViewController:splitVC];
    }
    else
    {
        masterViewController.juceViewController = juceViewController;
        detailNavController = [[UINavigationController alloc] initWithRootViewController: masterViewController];
        [window setRootViewController:detailNavController];
    }
    
    NSDictionary *navbarTitleTextAttributes = [NSDictionary dictionaryWithObjectsAndKeys:
                                               [UIColor whiteColor],NSForegroundColorAttributeName, nil];
    [[UINavigationBar appearance] setTitleTextAttributes:navbarTitleTextAttributes];
    UINavigationBar.appearance.barTintColor = [UIColor whiteColor];
    UINavigationBar.appearance.tintColor = [UIColor blackColor];
    
    [window makeKeyAndVisible];
}
    
void MainWindow::closeButtonPressed()
{
    JUCEApplication::getInstance()->systemRequestedQuit();
}

void MainWindow::addComponentToUIView (Component& component, void* uiView)
{
    component.addToDesktop (0, uiView);
    UIView* view = (UIView*) uiView;
    component.setVisible (true);
    component.setBounds (view.bounds.origin.x, view.bounds.origin.y,
                    view.bounds.size.width, view.bounds.size.height);
}
